"""Configuration file management for installer."""

from __future__ import annotations

from pathlib import Path

from .commands import run_command
from .constants import (
    DEFAULT_ENV_FILE,
    DEFAULT_PYRIT_CONFIG_FILE,
    REQUIRED_ENV_DEFAULTS,
    REQUIRED_PYRIT_DEFAULTS,
    SAMPLE_DIR,
)
from .prompts import prompt, prompt_multiline_defaults


def write_text_file(*, path: Path, content: str) -> None:
    """Write UTF-8 text content creating parent folders if needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def write_env_file(*, values: dict[str, str], path: Path) -> None:
    """Write .env.local in deterministic key order."""
    ordered_keys = list(REQUIRED_ENV_DEFAULTS.keys())
    extra_keys = sorted(key for key in values.keys() if key not in REQUIRED_ENV_DEFAULTS)
    lines = ["# Generated by install_security-evaluator.py"]
    for key in ordered_keys + extra_keys:
        if key in values:
            lines.append(f"{key}={values[key]}")
    write_text_file(path=path, content="\n".join(lines) + "\n")


def upsert_env_values(*, path: Path, updates: dict[str, str]) -> None:
    """Create/update environment values while preserving existing keys."""
    existing: dict[str, str] = {}
    if path.exists():
        for raw_line in path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            existing[key.strip()] = value.strip()
    merged = {**existing, **updates}
    write_env_file(values=merged, path=path)


def write_pyrit_config_file(*, env_file: Path, operator: str, operation: str, path: Path) -> None:
    """Write .pyrit_config with selected metadata and env file entry."""
    env_reference = f"./{env_file.name}"
    content = {
        **REQUIRED_PYRIT_DEFAULTS,
        "operator": operator,
        "operation": operation,
        "env_files": [env_reference],
    }
    yaml_lines = [
        "# Generated by install_security-evaluator.py",
        f"memory_db_type: {content['memory_db_type']}",
        f"operator: {content['operator']}",
        f"operation: {content['operation']}",
        "initializers: []",
        "env_files:",
        f"  - {content['env_files'][0]}",
        f"silent: {str(content['silent']).lower()}",
    ]
    write_text_file(path=path, content="\n".join(yaml_lines) + "\n")


def validate_configuration(*, python_exe: str) -> int:
    """Run configuration validation script."""
    validator = SAMPLE_DIR / "scripts" / "helper" / "verification" / "validate_redteam_config.py"
    return run_command([python_exe, str(validator)], cwd=SAMPLE_DIR)


def write_configs_interactively() -> None:
    """Prompt user for config values and write files."""
    env_values = prompt_multiline_defaults(defaults=REQUIRED_ENV_DEFAULTS)
    write_env_file(values=env_values, path=DEFAULT_ENV_FILE)
    print(f"Wrote {DEFAULT_ENV_FILE}")

    operator = prompt(message="PyRIT operator name", default="local_redteam")
    operation = prompt(message="PyRIT operation name", default="owasp_ollama_example")
    write_pyrit_config_file(
        env_file=DEFAULT_ENV_FILE,
        operator=operator,
        operation=operation,
        path=DEFAULT_PYRIT_CONFIG_FILE,
    )
    print(f"Wrote {DEFAULT_PYRIT_CONFIG_FILE}")
